In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('DOH_data/DOHDataDrop20200806-Changelog.xlsx')

In [3]:
df.groupby(['CaseCode'])

In [4]:
df.head(20)

   CaseCode             Column            Old Value            New Value
0   C100218          DateOnset  2020-04-02 00:00:00                  NaN
1   C100264  DateResultRelease  2020-03-25 00:00:00                  NaN
2   C100426         CityMunRes                  NaN       CITY OF MANILA
3   C100426       CityMuniPSGC                  NaN          PH133901000
4   C100426                Age                   28                   29
5   C100426            ProvRes                  NaN                  NCR
6   C100434        DateRecover                  NaN  2020-07-17 00:00:00
7   C100956  DateResultRelease  2020-07-16 00:00:00                  NaN
8   C101015          DateOnset  2020-03-26 00:00:00  2020-03-25 00:00:00
9   C101762       HealthStatus         ASYMPTOMATIC             CRITICAL
10  C102026          DateOnset                  NaN  2020-07-28 00:00:00
11  C102116          DateOnset                  NaN  2020-07-10 00:00:00
12  C102129        DateRecover                  NaN  2020-07-25 00:00:00
13  C102611           Admitted                   NO                  YES
14  C102611          DateOnset                  NaN  2020-06-19 00:00:00
15  C102611       DateSpecimen  2020-06-18 00:00:00  2020-06-19 00:00:00
16  C103004        DateRecover                  NaN  2020-07-17 00:00:00
17  C103328       CityMuniPSGC          PH133902000          PH133904000
18  C103328          DateOnset  2020-05-28 00:00:00                  NaN
19  C104074          DateOnset                  NaN  2020-04-30 00:00:00